# Generated by Django 4.2.23 on 2025-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='date_created',
        ),
        migrations.AddField(
            model_name='snippet',
            name='code_file',
            field=models.FileField(blank=True, null=True, upload_to='snippets/'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
