# Generated by Django 4.2.23 on 2025-06-23 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_date_created_snippet_code_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
